# Generated by Django 6.0.5 on 2026-05-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_nullable_user_fk_for_account_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon_attribution',
            field=models.TextField(blank=True),
        ),
    ]
