# Generated by Django 6.0.5 on 2026-06-10 15:02

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def _dedupe(model, field):
    """Keep only the most recently updated row per token/endpoint value.

    Required before the unique constraint lands: historic registrations could
    create the same token under several users (logout/re-login on a shared
    device) or duplicate rows per user.  The newest row reflects the device's
    current owner.
    """
    duplicated = (
        model.objects.values(field)
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )
    for entry in duplicated:
        rows = model.objects.filter(**{field: entry[field]}).order_by("-updated_at", "-id")
        for stale in rows[1:]:
            stale.delete()


def dedupe_push_endpoints(apps, _schema_editor):
    _dedupe(apps.get_model("notifications", "DeviceToken"), "token")
    _dedupe(apps.get_model("notifications", "WebPushSubscription"), "endpoint")


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_vapidkey'),
    ]

    operations = [
        migrations.RunPython(dedupe_push_endpoints, migrations.RunPython.noop),
        migrations.AddField(
            model_name='devicetoken',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webpushsubscription',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='webpushsubscription',
            name='endpoint',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='ExpoPushTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.devicetoken')),
            ],
        ),
    ]
