# Generated by Django 6.0.6 on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("currency", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="CurrencyRateSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_currency", models.CharField(max_length=3)),
                ("rates", models.JSONField()),
                ("source", models.CharField(max_length=80)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-fetched_at"]},
        ),
    ]
