# Generated by Django on 2026-06-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("currency", "0002_currencyratesnapshot")]

    operations = [
        migrations.DeleteModel(
            name="ExchangeRate",
        ),
    ]
