# Generated by Django on 2026-06-28

from django.db import migrations, models
from django.utils import timezone


def backfill_rate_date(apps, schema_editor):
    snapshot_model = apps.get_model("currency", "CurrencyRateSnapshot")
    for snapshot in snapshot_model.objects.filter(rate_date__isnull=True).iterator():
        snapshot.rate_date = snapshot.fetched_at.date()
        snapshot.save(update_fields=["rate_date"])


class Migration(migrations.Migration):
    dependencies = [("currency", "0003_remove_exchangerate")]

    operations = [
        migrations.AddField(
            model_name="currencyratesnapshot",
            name="rate_date",
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.RunPython(backfill_rate_date, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="currencyratesnapshot",
            name="rate_date",
            field=models.DateField(db_index=True, default=timezone.localdate),
        ),
    ]
