# Generated by Django 4.2.30 on 2026-05-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('explicit', 'Explicit'), ('shared_group', 'Shared group')], default='explicit', max_length=20)),
                ('default_currency', models.CharField(default='EUR', max_length=3)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('participant_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_a', to='participants.participant')),
                ('participant_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_b', to='participants.participant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('participant_a', 'participant_b', 'source'), name='unique_friendship_pair_source'),
        ),
    ]
