// Single source of truth for the URL path the web/PWA app is served under.
//
// This is a fixed value, not configurable: the app always lives at `<origin>/app`
// (web, PWA and Android deep links), while the JSON API stays at `<origin>/api`.
// It mirrors `expo.experiments.baseUrl` in app.json and `APP_BASE_PATH` on the
// backend — all three are the literal "/app". This constant is used to:
//   - strip the prefix off incoming deep-link paths before React Navigation
//     parses them (getStateFromPath)
//   - re-add the prefix to generated paths so the web URL bar / shared links
//     stay under /app (getPathFromState)
export const BASE_PATH = "/app";

/**
 * Remove a leading {@link BASE_PATH} from a path (the part React Navigation
 * matches against the screen config). Preserves any query string / hash and
 * always returns a path with a leading slash. A no-op when the path is not under
 * the prefix (e.g. custom-scheme `splex://` deep links).
 */
export function stripBasePath(path: string): string {
  if (path === BASE_PATH) return "/";
  for (const boundary of ["/", "?", "#"]) {
    if (path.startsWith(BASE_PATH + boundary)) {
      const rest = path.slice(BASE_PATH.length);
      return rest.startsWith("/") ? rest : "/" + rest;
    }
  }
  return path;
}

/**
 * Prepend {@link BASE_PATH} to a path generated by React Navigation so the web
 * URL bar and shared links live under /app.
 */
export function addBasePath(path: string): string {
  return BASE_PATH + (path.startsWith("/") ? path : "/" + path);
}

type RouteLike = { path?: string; state?: StateLike };
type StateLike = { index?: number; routes: RouteLike[] };

/**
 * Re-add {@link BASE_PATH} to the focused route's stored `path` in a navigation
 * state produced by the default `getStateFromPath`.
 *
 * React Navigation records the parsed URL on the focused route's `path` and, on
 * web, echoes that value straight back into the address bar on the initial page
 * load — bypassing `getPathFromState`. Because we feed it the base-path-stripped
 * path (e.g. "/login"), that stored value would otherwise drop the prefix and
 * the URL would become "/login" instead of "/app/login". This restores it.
 */
export function restoreBasePathInState<T extends StateLike>(state: T): T {
  const index = state.index ?? state.routes.length - 1;
  const routes = state.routes.map((route, i) => {
    if (i !== index) return route;
    if (route.state) {
      return { ...route, state: restoreBasePathInState(route.state) };
    }
    if (typeof route.path === "string") {
      return { ...route, path: addBasePath(stripBasePath(route.path)) };
    }
    return route;
  });
  return { ...state, routes };
}
