from django.conf import settings
from django.db import models

from splex.shared.managers import SoftDeletableManager
from splex.shared.models import TimeStampedModel


class Settlement(TimeStampedModel):
    SOFT_DELETE_FIELD = "deleted_at"

    class Kind(models.TextChoices):
        # Recorded by a user via the "settle" UI - i.e. a real payment between two members.
        MANUAL = "manual", "Manual"
        # Auto-generated by the backend to zero out balances when an unregistered
        # participant is removed from a group. No real money changed hands; the
        # row exists purely to keep group ledgers consistent. UIs should label
        # these as write-offs rather than as settlements.
        AUTO_WRITE_OFF = "auto_write_off", "Auto write-off"

    client_id = models.CharField(max_length=64, blank=True)
    group = models.ForeignKey("groups.Group", null=True, blank=True, on_delete=models.CASCADE)
    friendship = models.ForeignKey(
        "friends.Friendship", null=True, blank=True, on_delete=models.CASCADE
    )
    payer_participant = models.ForeignKey(
        "participants.Participant", on_delete=models.PROTECT, related_name="settlements_paid"
    )
    receiver_participant = models.ForeignKey(
        "participants.Participant", on_delete=models.PROTECT, related_name="settlements_received"
    )
    original_amount = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    original_currency = models.CharField(max_length=3, default="EUR")
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    currency = models.CharField(max_length=3)
    exchange_rate = models.DecimalField(max_digits=18, decimal_places=8, default=1)
    exchange_rate_source = models.CharField(max_length=80, default="identity")
    kind = models.CharField(max_length=20, choices=Kind.choices, default=Kind.MANUAL)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL
    )
    deleted_at = models.DateTimeField(null=True, blank=True)

    objects = SoftDeletableManager()
