# Generated by Django 6.0.5 on 2026-05-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_tracking_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
