# Generated by Django 6.0.5 on 2026-05-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_location_tracking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_attribution',
            field=models.TextField(blank=True),
        ),
    ]
