# Generated by Django 6.0.5 on 2026-05-29 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_retention_warning_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('paypal_handle', 'PayPal handle'), ('paypal_email', 'PayPal email')], max_length=32)),
                ('identifier', models.CharField(max_length=254)),
                ('is_preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_preferred', 'created_at'],
                'indexes': [models.Index(fields=['user', 'is_preferred'], name='payment_user_preferred_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'identifier'), name='payment_unique_per_kind_identifier')],
            },
        ),
    ]
