# Generated by Django 6.0.5 on 2026-06-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='magicloginchallenge',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
