# Generated by Django 4.2.30 on 2026-05-14 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participants', '0001_initial'),
        ('friends', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(max_length=240)),
                ('date', models.DateField()),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_currency', models.CharField(max_length=3)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('converted_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=1, max_digits=18)),
                ('exchange_rate_source', models.CharField(default='identity', max_length=80)),
                ('split_method', models.CharField(choices=[('equal_all', 'Equal all'), ('equal_selected', 'Equal selected'), ('percentage', 'Percentage'), ('exact', 'Exact'), ('adjusted_equal', 'Adjusted equal')], max_length=32)),
                ('split_metadata', models.JSONField(blank=True, default=dict)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('friendship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.friendship')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpensePaymentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_shares', to='expenses.expense')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseOwedShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owed_shares', to='expenses.expense')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.participant')),
            ],
        ),
    ]
