# Generated by Django 6.0.5 on 2026-05-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_nullable_user_fk_for_account_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approximate_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expense',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
