# Generated by Django 6.0.5 on 2026-05-23 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_location_precision'),
        ('friends', '0003_partial_unique_active_friendship'),
        ('groups', '0005_nullable_user_fk_for_account_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id', ''), _negated=True), fields=('created_by', 'client_id'), name='expense_unique_client_id_per_user'),
        ),
    ]
