# Generated by Django 6.0.5 on 2026-05-26 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expense_expense_unique_client_id_per_user'),
        ('friends', '0003_partial_unique_active_friendship'),
        ('groups', '0006_group_icon_attribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('storage_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('image/jpeg', 'JPEG'), ('image/png', 'PNG'), ('image/webp', 'WebP'), ('application/pdf', 'PDF')], max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='expenses.expense')),
                ('friendship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.friendship')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='groups.group')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['uploaded_by', 'client_id'], name='expenses_re_uploade_df2261_idx'), models.Index(fields=['group'], name='expenses_re_group_i_8a963b_idx'), models.Index(fields=['friendship'], name='expenses_re_friends_e28b2f_idx'), models.Index(fields=['expense'], name='expenses_re_expense_eb22cc_idx')],
            },
        ),
    ]
