# Generated by Django on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("expenses", "0008_receipt")]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="exchange_rate_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
