# Generated by Django on 2026-06-28

from decimal import Decimal

from django.db import migrations, models


def backfill_original_rate_fields(apps, schema_editor):
    settlement_model = apps.get_model("settlements", "Settlement")
    for settlement in settlement_model.objects.all().iterator():
        settlement.original_amount = settlement.amount
        settlement.original_currency = settlement.currency
        settlement.exchange_rate = Decimal("1")
        settlement.exchange_rate_source = "identity"
        settlement.save(
            update_fields=[
                "original_amount",
                "original_currency",
                "exchange_rate",
                "exchange_rate_source",
            ]
        )


class Migration(migrations.Migration):
    dependencies = [("settlements", "0003_settlement_kind")]

    operations = [
        migrations.AddField(
            model_name="settlement",
            name="original_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="settlement",
            name="original_currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
        migrations.AddField(
            model_name="settlement",
            name="exchange_rate",
            field=models.DecimalField(decimal_places=8, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name="settlement",
            name="exchange_rate_source",
            field=models.CharField(default="identity", max_length=80),
        ),
        migrations.RunPython(backfill_original_rate_fields, migrations.RunPython.noop),
    ]
