from enum import StrEnum
from math import ceil

from django.core.exceptions import PermissionDenied
from django.http import Http404
from rest_framework.exceptions import (
    AuthenticationFailed,
    MethodNotAllowed,
    NotAuthenticated,
    NotFound,
    Throttled,
    UnsupportedMediaType,
    ValidationError,
)
from rest_framework.exceptions import (
    PermissionDenied as DrfPermissionDenied,
)
from rest_framework.response import Response
from rest_framework.views import exception_handler as drf_exception_handler

from splex.shared.errors import ApiResponseError, NormalizedApiError


class ApiErrorCode(StrEnum):
    """Stable codes for errors generated by Django REST Framework itself.

    Keep these separate from ``ErrorCode``: framework exceptions are mapped at
    the HTTP boundary, while ``ErrorCode`` belongs to Splex domain services.
    """

    AUTHENTICATION_FAILED = "authentication_failed"
    API_ERROR = "api_error"
    METHOD_NOT_ALLOWED = "method_not_allowed"
    NOT_FOUND = "not_found"
    PERMISSION_DENIED = "permission_denied"
    THROTTLED = "throttled"
    UNSUPPORTED_MEDIA_TYPE = "unsupported_media_type"
    VALIDATION_ERROR = "validation_error"


ERROR_CODES_BY_EXCEPTION = (
    # The single registry for translating DRF exception classes into the
    # public error contract. Add a framework exception here, not in services.
    (Throttled, ApiErrorCode.THROTTLED),
    ((AuthenticationFailed, NotAuthenticated), ApiErrorCode.AUTHENTICATION_FAILED),
    ((DrfPermissionDenied, PermissionDenied), ApiErrorCode.PERMISSION_DENIED),
    ((NotFound, Http404), ApiErrorCode.NOT_FOUND),
    (MethodNotAllowed, ApiErrorCode.METHOD_NOT_ALLOWED),
    (UnsupportedMediaType, ApiErrorCode.UNSUPPORTED_MEDIA_TYPE),
    (ValidationError, ApiErrorCode.VALIDATION_ERROR),
)


def _error_code(exc: Exception) -> str:
    for exception_types, code in ERROR_CODES_BY_EXCEPTION:
        if isinstance(exc, exception_types):
            return code
    return ApiErrorCode.API_ERROR


def _framework_error(exc: Exception, response_data) -> NormalizedApiError:
    """Adapt a native DRF response without exposing its exception detail text."""
    fields = response_data if isinstance(exc, ValidationError) else None

    params = {}
    if isinstance(exc, Throttled) and exc.wait is not None:
        params = {"wait_seconds": ceil(exc.wait)}
    return NormalizedApiError(
        code=_error_code(exc),
        params=params,
        fields=fields,
    )


def exception_handler(exc, context):
    """Convert expected failures into a canonical error response at the HTTP boundary."""
    if isinstance(exc, ApiResponseError):
        return Response(exc.to_normalized_error().to_data(), status=exc.status)
    response = drf_exception_handler(exc, context)
    if response is None:
        return None

    response.data = _framework_error(exc, response.data).to_data()
    return response
